#!/bin/sh
PATH="/usr/local/bin:$PATH"

# Redirect output to stderr.
exec 1>&2

IS_ERROR=0
# ステージング(Addされたもの)で .php で終わるもの
for FILE in `git diff --cached --name-status HEAD -- | grep -E '^[AUM].*\.php$'| cut -c3-`; do
    # シンタックスのチェック
    if php -l $FILE; then
        # PSR準拠でコード書き換え
        # php-cs-fixer のオプション指定は以下を参照
        # https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/UPGRADE.md#cli-options
        php-cs-fixer fix $FILE --rules='{"@PSR2":true, "phpdoc_align":true, "include": true, "blank_line_after_opening_tag":true, "blank_line_before_return":true, "binary_operator_spaces":{"align_double_arrow":true, "align_equals":false}, "concat_space":{"spacing":"none"}, "function_typehint_space":true, "lowercase_cast":true, "no_blank_lines_after_class_opening":true, "no_blank_lines_after_phpdoc":true, "no_trailing_comma_in_singleline_array": true, "no_whitespace_before_comma_in_array":true, "not_operator_with_successor_space":true, "object_operator_without_whitespace":true, "single_quote":true, "space_after_semicolon":true, "standardize_not_equals":true, "ternary_operator_spaces":true, "whitespace_after_comma_in_array":true, "array_syntax":{"syntax":"short"}}'
        git add $FILE

        # PHPMDで未使用変数のチェック
        if ! phpmd $FILE text unusedcode; then
            IS_ERROR=1
        fi
    else
        IS_ERROR=1
    fi
done
exit $IS_ERROR
